[package]
name = "tsv_wasm"
version.workspace = true
edition.workspace = true
description = "TypeScript and Svelte tools - WebAssembly bindings"
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.wasm-pack.profile.release]
# Disable wasm-opt until it supports bulk memory operations from Rust 2024
wasm-opt = false

[dependencies]
tsv_svelte.workspace = true
tsv_ts.workspace = true
tsv_css.workspace = true
wasm-bindgen = "0.2"
serde-wasm-bindgen = "0.6"
serde_json.workspace = true

[lints]
workspace = true
