//! The ratchet/snapshot plumbing: the committed shape snapshot (`gap_audit_known.txt`),
//! its [`KnownKey`] line format, and the panic/pinnable bookkeeping around it. Split out
//! of `gap_audit.rs` for navigability.

use std::collections::{BTreeMap, BTreeSet};
use std::path::PathBuf;

use crate::audit::ratchet::{Ratchet, SnapshotKey};

use super::{Kind, ShapeAgg};

/// The command that re-pins the snapshot — quoted by the ratchet's read-failure message.
const REPIN_HINT: &str = "deno task gaps:audit:update";

/// The `#`-comment header the snapshot file opens with — machine-generated, do NOT
/// hand-edit. Owned here (not by the [`Ratchet`]) because it documents *this* audit's
/// ratchet: what a line means, why counts aren't pinned, why a panic is never listed.
const SNAPSHOT_HEADER: &str = "# Generated by `deno task gaps:audit:update` — do NOT hand-edit.\n\
     #\n\
     # Every line is a KNOWN BUG: a site shape where injecting a comment makes the\n\
     # formatter drop or double-print one. The gate fails on a line that is NOT here\n\
     # (a new kind of drop) and on a line here that no longer fires (a stale entry —\n\
     # delete it when you fix one). Counts are deliberately not pinned: they churn with\n\
     # every ordinary fixture PR, and a gate that fails per added fixture gets turned\n\
     # off. The PAYLOAD set is pinned, though: a shape that starts dropping a comment\n\
     # kind it used to survive is a new bug on a new ownership path.\n\
     #\n\
     # A PANIC is never listed here — that invariant is absolute, so it always fails\n\
     # the gate rather than being pinned.\n\
     #\n\
     # Format: KIND<TAB>SHAPE<TAB>PAYLOADS\n";

/// Where the committed shape snapshot lives — the ratchet `deno task check` gates on.
///
/// The snapshot is **machine-generated** (`deno task gaps:audit:update`), unlike
/// [`scan_audit`](crate::cli::commands::scan_audit)'s hand-curated `ALLOW`: at ~700 shapes
/// a per-entry rationale is not a thing a human can keep honest, so it deliberately
/// carries none. It is a ratchet, not a sanction — every line is a **known bug**, and the
/// file shrinking is the goal.
///
/// Colocated with this module so it travels with the code that owns it. The path is the
/// only compile-time piece (`CARGO_MANIFEST_DIR`); the file itself is read at runtime by the
/// [`Ratchet`] — see [`audit::ratchet`](crate::audit::ratchet) for why not `include_str!`.
pub(super) fn known_shapes_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("src/cli/commands/gap_audit_known.txt")
}

/// The ratchet over [`known_shapes_path`], carrying this audit's header + re-pin hint.
pub(super) fn ratchet() -> Ratchet {
    Ratchet::new(known_shapes_path(), SNAPSHOT_HEADER, REPIN_HINT)
}

/// One snapshot line: what the ratchet actually pins.
///
/// The payload set is part of the key, not decoration. A shape that drops only a `line`
/// comment today and starts dropping a `block` one tomorrow is a **new bug on a new
/// ownership path** — keyed on the shape alone it would land inside an existing entry and
/// never be seen. It is also stable in the way a count is not: it changes when the bug's
/// character changes, not when a fixture is added.
///
/// [`Kind`] leads the key, so its derived [`Ord`] matches the `shapes` map's `(Kind, shape)`
/// order — the snapshot renders in exactly that order, giving a stable, minimal-diff file.
#[derive(Clone, PartialEq, Eq, PartialOrd, Ord, Debug)]
pub(super) struct KnownKey {
    pub(super) kind: Kind,
    pub(super) shape: String,
    pub(super) payloads: String,
}

impl SnapshotKey for KnownKey {
    fn to_line(&self) -> String {
        format!("{}\t{}\t{}", self.kind.label(), self.shape, self.payloads)
    }

    fn from_line(line: &str) -> Option<Self> {
        let mut cols = line.split('\t');
        let kind = Kind::from_label(cols.next()?)?;
        let shape = cols.next()?.to_string();
        let payloads = cols.next()?.to_string();
        Some(Self {
            kind,
            shape,
            payloads,
        })
    }

    fn is_pinnable(&self) -> bool {
        is_pinnable(self.kind)
    }
}

/// Render a payload set into its snapshot column.
fn payload_column(payloads: &BTreeSet<&'static str>) -> String {
    payloads.iter().copied().collect::<Vec<_>>().join(",")
}

/// Every shape as a [`KnownKey`] — **including** the unpinnable (`PANIC`) ones. The
/// [`Ratchet`] filters those out of the file and counts them on their own (see
/// [`SnapshotKey::is_pinnable`]), so the caller hands it the whole set and the split lives
/// in one place.
pub(super) fn snapshot_keys(shapes: &BTreeMap<(Kind, String), ShapeAgg>) -> BTreeSet<KnownKey> {
    shapes
        .iter()
        .map(|((kind, shape), agg)| KnownKey {
            kind: *kind,
            shape: shape.clone(),
            payloads: payload_column(&agg.payloads),
        })
        .collect()
}

/// Whether a shape is something the snapshot may pin — everything but a [`Kind::Panic`].
///
/// A panic is not a "known bug" to ratchet alongside the drops. The invariant it breaks is
/// **absolute** (a comment in a gap must never crash the formatter), so it always fails the
/// gate and is never pinnable — otherwise `--update` would quietly absorb a crash into the
/// same list whose shrinking is the goal. [`KnownKey::is_pinnable`] routes through this, so
/// the ratchet's render/grade and the panic accounting below stay in lockstep.
pub(super) fn is_pinnable(kind: Kind) -> bool {
    kind != Kind::Panic
}

/// How many of `shapes` crash the formatter — the shapes [`is_pinnable`] keeps out of the
/// snapshot, and which therefore need their own accounting on every exit path (the ratchet's
/// `GateDiff::unpinnable` is the abstract count; this is the concrete panic set gap reports
/// with examples).
pub(super) fn count_panics(shapes: &BTreeMap<(Kind, String), ShapeAgg>) -> usize {
    shapes.keys().filter(|(k, _)| *k == Kind::Panic).count()
}

#[cfg(test)]
mod tests {
    use super::super::Example;
    use super::*;

    /// A minimal shape carrying `payloads` — only the snapshot columns matter here, so the
    /// example is filler.
    fn mk_agg(payloads: &[&'static str]) -> ShapeAgg {
        ShapeAgg {
            count: 1,
            payloads: payloads.iter().copied().collect(),
            bystander_hits: 0,
            files: BTreeSet::new(),
            examples: vec![Example {
                payload: "block",
                path: "p.svelte".to_string(),
                injection_offset: 0,
                attribution_offset: 0,
                snippet: String::new(),
                text: "/* c */".to_string(),
                injected: true,
            }],
            verify: None,
        }
    }

    /// The snapshot is the gate's on-disk contract: whatever `--update` writes, the gate
    /// must read back as the identical key set, or a green run means nothing.
    #[test]
    fn snapshot_render_and_parse_round_trip() {
        let mut shapes: BTreeMap<(Kind, String), ShapeAgg> = BTreeMap::new();
        shapes.insert((Kind::Dropped, "import⟨⟩.".to_string()), mk_agg(&["block"]));
        shapes.insert(
            (Kind::DoublePrinted, "IDENT⟨⟩=".to_string()),
            mk_agg(&["line", "block"]),
        );

        let r = Ratchet::new(PathBuf::from("/unused"), SNAPSHOT_HEADER, REPIN_HINT);
        let found = snapshot_keys(&shapes);
        let rendered = r.render(&found);
        // Every non-comment line must parse back to a complete key — a dropped column would
        // make the gate silently compare fewer fields than it pins.
        let parsed: BTreeSet<KnownKey> = rendered
            .lines()
            .filter(|l| !l.is_empty() && !l.starts_with('#'))
            .filter_map(KnownKey::from_line)
            .collect();

        assert_eq!(parsed, found, "render → parse must round-trip");
        // The payload column is part of the key: same shape, different payload set ⇒
        // different entry, so a shape that starts dropping a new comment kind fails the gate.
        // Kind leads the key, so the DROPPED shape renders before the DOUBLE-PRINTED one.
        assert!(rendered.contains("DROPPED\timport⟨⟩.\tblock\n"));
        assert!(rendered.contains("DOUBLE-PRINTED\tIDENT⟨⟩=\tblock,line\n"));
    }

    /// The committed snapshot's line ORDER is load-bearing for byte-identity: `--update`
    /// renders in [`KnownKey`]'s [`Ord`] order, and `gap_audit_known.txt` is committed in
    /// **`Kind`-enum** order — all `DROPPED`, then all `DOUBLE-PRINTED`. That is NOT
    /// label-string order, which would put `DOUBLE-PRINTED` first (`'O' < 'R'`). Two facts
    /// nothing else pins carry it: (1) `KnownKey.kind` is the [`Kind`] **enum**
    /// (`Dropped` = 0 < `DoublePrinted` = 1), not a label `String`; (2) `kind` is the
    /// **first** field of the derived `Ord`. Flip either — retype `kind` to a `String`, or
    /// reorder the struct fields — and this exact-vector assert fails, where
    /// `snapshot_render_and_parse_round_trip` (order-agnostic `contains`) and the gate
    /// (set-difference grade, order-independent) both stay green, and the break would only
    /// surface as a ~700-line reorder the next time someone runs `--update`. The line text
    /// also locks the `kind<TAB>shape<TAB>payloads` column order.
    #[test]
    fn render_orders_by_kind_enum_not_label() {
        let mut shapes: BTreeMap<(Kind, String), ShapeAgg> = BTreeMap::new();
        // Shapes chosen so enum-order and label-string-order DISAGREE, and a field reorder
        // (shape-first) also flips them: `'I' < 'i'`, so shape order would render the
        // DOUBLE-PRINTED `IDENT⟨⟩=` before the DROPPED `import⟨⟩.`.
        shapes.insert((Kind::Dropped, "import⟨⟩.".to_string()), mk_agg(&["block"]));
        shapes.insert(
            (Kind::DoublePrinted, "IDENT⟨⟩=".to_string()),
            mk_agg(&["line", "block"]),
        );

        let r = Ratchet::new(PathBuf::from("/unused"), SNAPSHOT_HEADER, REPIN_HINT);
        let rendered = r.render(&snapshot_keys(&shapes));
        let data: Vec<&str> = rendered
            .lines()
            .filter(|l| !l.is_empty() && !l.starts_with('#'))
            .collect();
        assert_eq!(
            data,
            vec![
                "DROPPED\timport⟨⟩.\tblock",
                "DOUBLE-PRINTED\tIDENT⟨⟩=\tblock,line",
            ],
            "snapshot renders in Kind-enum order (DROPPED before DOUBLE-PRINTED), not \
             label-string order; each line is kind<TAB>shape<TAB>payloads"
        );
    }

    /// A panic must never reach the snapshot — not via `--update`, and not as a key the
    /// gate diffs. The corpus cannot grade this: `tests/fixtures` panics nowhere today, so
    /// both arms are vacuously green there and would stay green if the filter were dropped.
    #[test]
    fn a_panic_is_never_pinned() {
        let mut shapes: BTreeMap<(Kind, String), ShapeAgg> = BTreeMap::new();
        shapes.insert((Kind::Dropped, "import⟨⟩.".to_string()), mk_agg(&["block"]));
        shapes.insert((Kind::Panic, "IDENT⟨⟩(".to_string()), mk_agg(&["block"]));

        let r = Ratchet::new(PathBuf::from("/unused"), SNAPSHOT_HEADER, REPIN_HINT);
        let found = snapshot_keys(&shapes);

        // Not written: a crash must not land in the list whose shrinking is the goal.
        // Checked over the DATA lines, not the whole file — the header explains the panic
        // rule in prose, so a substring search over it matches that and proves nothing.
        let rendered = r.render(&found);
        let data: Vec<&str> = rendered
            .lines()
            .filter(|l| !l.is_empty() && !l.starts_with('#'))
            .collect();
        assert_eq!(
            data,
            vec!["DROPPED\timport⟨⟩.\tblock"],
            "only the pinnable shape is written"
        );

        // Nor pinnable: the panic is in the found set but never a pinned key.
        let pinnable: Vec<_> = found.iter().filter(|k| k.is_pinnable()).collect();
        assert_eq!(pinnable.len(), 1, "only the pinnable shape is a key");
        assert!(pinnable.iter().all(|k| k.kind != Kind::Panic));

        assert_eq!(
            count_panics(&shapes),
            1,
            "but it is still counted, and fails"
        );
    }
}
