[package]
name = "tsv_ts"
version.workspace = true
edition.workspace = true
description = "TypeScript parsing and formatting library"

[dependencies]
tsv_lang.workspace = true
serde.workspace = true
serde_json.workspace = true
string-interner.workspace = true
phf = { version = "0.11", features = ["macros"] }

[lints]
workspace = true
